name = "AdaptiveLevin"
uuid = "cb2033fd-04a4-45e1-a176-a3c784c945f7"
authors = ["Yucheng Yin <cuber.ycyin@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1"  
LinearAlgebra = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
